[2024-01-27 15:48:50|21284|INFO|base_model.py:91]  session [2041137035248] and [RegressPredict] has an operator: QUERY.
[2024-01-27 15:48:51|21284|ERROR|__init__.py:110]  sha2_rsa_encrypt error, info is 'cryptography' package is required for sha256_password or caching_sha2_password auth methods
[2024-01-27 15:48:51|21284|ERROR|__init__.py:111]  Traceback (most recent call last):
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "F:\python\LogisticsDesign\back_end\views\sales_view.py", line 19, in init
    query_result = rp.query([rp.id, rp.operate, rp.create_time])
  File "F:\python\LogisticsDesign\database\base_model.py", line 121, in query
    return s_query.all()
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\sqlalchemy\orm\query.py", line 2693, in all
    return self._iter().all()  # type: ignore
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\sqlalchemy\orm\query.py", line 2847, in _iter
    result: Union[ScalarResult[_T], Result[_T]] = self.session.execute(
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\sqlalchemy\orm\session.py", line 2308, in execute
    return self._execute_internal(
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\sqlalchemy\orm\session.py", line 2180, in _execute_internal
    conn = self._connection_for_bind(bind)
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\sqlalchemy\orm\session.py", line 2047, in _connection_for_bind
    return trans._connection_for_bind(engine, execution_options)
  File "<string>", line 2, in _connection_for_bind
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\sqlalchemy\orm\state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\sqlalchemy\orm\session.py", line 1143, in _connection_for_bind
    conn = bind.connect()
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\sqlalchemy\engine\base.py", line 3269, in connect
    return self._connection_cls(self)
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\sqlalchemy\engine\base.py", line 145, in __init__
    self._dbapi_connection = engine.raw_connection()
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\sqlalchemy\engine\base.py", line 3293, in raw_connection
    return self.pool.connect()
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\sqlalchemy\pool\base.py", line 452, in connect
    return _ConnectionFairy._checkout(self)
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\sqlalchemy\pool\base.py", line 1269, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\sqlalchemy\pool\base.py", line 716, in checkout
    rec = pool._do_get()
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\sqlalchemy\pool\impl.py", line 169, in _do_get
    with util.safe_reraise():
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\sqlalchemy\util\langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\sqlalchemy\pool\impl.py", line 167, in _do_get
    return self._create_connection()
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\sqlalchemy\pool\base.py", line 393, in _create_connection
    return _ConnectionRecord(self)
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\sqlalchemy\pool\base.py", line 678, in __init__
    self.__connect()
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\sqlalchemy\pool\base.py", line 902, in __connect
    with util.safe_reraise():
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\sqlalchemy\util\langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\sqlalchemy\pool\base.py", line 898, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\sqlalchemy\engine\create.py", line 645, in connect
    return dialect.connect(*cargs, **cparams)
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\sqlalchemy\engine\default.py", line 616, in connect
    return self.loaded_dbapi.connect(*cargs, **cparams)
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\pymysql\connections.py", line 358, in __init__
    self.connect()
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\pymysql\connections.py", line 664, in connect
    self._request_authentication()
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\pymysql\connections.py", line 976, in _request_authentication
    auth_packet = _auth.caching_sha2_password_auth(self, auth_packet)
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\pymysql\_auth.py", line 266, in caching_sha2_password_auth
    data = sha2_rsa_encrypt(conn.password, conn.salt, conn.server_public_key)
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\pymysql\_auth.py", line 143, in sha2_rsa_encrypt
    raise RuntimeError(
RuntimeError: 'cryptography' package is required for sha256_password or caching_sha2_password auth methods

[2024-01-27 15:48:51|22948|INFO|base_model.py:91]  session [2041137614272] and [RegressPredict] has an operator: QUERY.
[2024-01-27 15:48:51|22948|ERROR|__init__.py:110]  sha2_rsa_encrypt error, info is 'cryptography' package is required for sha256_password or caching_sha2_password auth methods
[2024-01-27 15:48:51|22948|ERROR|__init__.py:111]  Traceback (most recent call last):
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "F:\python\LogisticsDesign\back_end\views\sales_view.py", line 19, in init
    query_result = rp.query([rp.id, rp.operate, rp.create_time])
  File "F:\python\LogisticsDesign\database\base_model.py", line 121, in query
    return s_query.all()
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\sqlalchemy\orm\query.py", line 2693, in all
    return self._iter().all()  # type: ignore
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\sqlalchemy\orm\query.py", line 2847, in _iter
    result: Union[ScalarResult[_T], Result[_T]] = self.session.execute(
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\sqlalchemy\orm\session.py", line 2308, in execute
    return self._execute_internal(
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\sqlalchemy\orm\session.py", line 2180, in _execute_internal
    conn = self._connection_for_bind(bind)
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\sqlalchemy\orm\session.py", line 2047, in _connection_for_bind
    return trans._connection_for_bind(engine, execution_options)
  File "<string>", line 2, in _connection_for_bind
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\sqlalchemy\orm\state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\sqlalchemy\orm\session.py", line 1143, in _connection_for_bind
    conn = bind.connect()
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\sqlalchemy\engine\base.py", line 3269, in connect
    return self._connection_cls(self)
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\sqlalchemy\engine\base.py", line 145, in __init__
    self._dbapi_connection = engine.raw_connection()
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\sqlalchemy\engine\base.py", line 3293, in raw_connection
    return self.pool.connect()
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\sqlalchemy\pool\base.py", line 452, in connect
    return _ConnectionFairy._checkout(self)
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\sqlalchemy\pool\base.py", line 1269, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\sqlalchemy\pool\base.py", line 716, in checkout
    rec = pool._do_get()
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\sqlalchemy\pool\impl.py", line 169, in _do_get
    with util.safe_reraise():
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\sqlalchemy\util\langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\sqlalchemy\pool\impl.py", line 167, in _do_get
    return self._create_connection()
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\sqlalchemy\pool\base.py", line 393, in _create_connection
    return _ConnectionRecord(self)
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\sqlalchemy\pool\base.py", line 678, in __init__
    self.__connect()
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\sqlalchemy\pool\base.py", line 902, in __connect
    with util.safe_reraise():
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\sqlalchemy\util\langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\sqlalchemy\pool\base.py", line 898, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\sqlalchemy\engine\create.py", line 645, in connect
    return dialect.connect(*cargs, **cparams)
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\sqlalchemy\engine\default.py", line 616, in connect
    return self.loaded_dbapi.connect(*cargs, **cparams)
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\pymysql\connections.py", line 358, in __init__
    self.connect()
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\pymysql\connections.py", line 664, in connect
    self._request_authentication()
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\pymysql\connections.py", line 976, in _request_authentication
    auth_packet = _auth.caching_sha2_password_auth(self, auth_packet)
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\pymysql\_auth.py", line 266, in caching_sha2_password_auth
    data = sha2_rsa_encrypt(conn.password, conn.salt, conn.server_public_key)
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\pymysql\_auth.py", line 143, in sha2_rsa_encrypt
    raise RuntimeError(
RuntimeError: 'cryptography' package is required for sha256_password or caching_sha2_password auth methods

[2024-01-27 15:49:33|10728|INFO|base_model.py:91]  session [1952566916480] and [RegressPredict] has an operator: QUERY.
[2024-01-27 15:49:33|10728|ERROR|__init__.py:110]  sha2_rsa_encrypt error, info is 'cryptography' package is required for sha256_password or caching_sha2_password auth methods
[2024-01-27 15:49:33|10728|ERROR|__init__.py:111]  Traceback (most recent call last):
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "F:\python\LogisticsDesign\back_end\views\sales_view.py", line 19, in init
    query_result = rp.query([rp.id, rp.operate, rp.create_time])
  File "F:\python\LogisticsDesign\database\base_model.py", line 121, in query
    return s_query.all()
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\sqlalchemy\orm\query.py", line 2693, in all
    return self._iter().all()  # type: ignore
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\sqlalchemy\orm\query.py", line 2847, in _iter
    result: Union[ScalarResult[_T], Result[_T]] = self.session.execute(
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\sqlalchemy\orm\session.py", line 2308, in execute
    return self._execute_internal(
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\sqlalchemy\orm\session.py", line 2180, in _execute_internal
    conn = self._connection_for_bind(bind)
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\sqlalchemy\orm\session.py", line 2047, in _connection_for_bind
    return trans._connection_for_bind(engine, execution_options)
  File "<string>", line 2, in _connection_for_bind
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\sqlalchemy\orm\state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\sqlalchemy\orm\session.py", line 1143, in _connection_for_bind
    conn = bind.connect()
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\sqlalchemy\engine\base.py", line 3269, in connect
    return self._connection_cls(self)
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\sqlalchemy\engine\base.py", line 145, in __init__
    self._dbapi_connection = engine.raw_connection()
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\sqlalchemy\engine\base.py", line 3293, in raw_connection
    return self.pool.connect()
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\sqlalchemy\pool\base.py", line 452, in connect
    return _ConnectionFairy._checkout(self)
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\sqlalchemy\pool\base.py", line 1269, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\sqlalchemy\pool\base.py", line 716, in checkout
    rec = pool._do_get()
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\sqlalchemy\pool\impl.py", line 169, in _do_get
    with util.safe_reraise():
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\sqlalchemy\util\langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\sqlalchemy\pool\impl.py", line 167, in _do_get
    return self._create_connection()
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\sqlalchemy\pool\base.py", line 393, in _create_connection
    return _ConnectionRecord(self)
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\sqlalchemy\pool\base.py", line 678, in __init__
    self.__connect()
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\sqlalchemy\pool\base.py", line 902, in __connect
    with util.safe_reraise():
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\sqlalchemy\util\langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\sqlalchemy\pool\base.py", line 898, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\sqlalchemy\engine\create.py", line 645, in connect
    return dialect.connect(*cargs, **cparams)
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\sqlalchemy\engine\default.py", line 616, in connect
    return self.loaded_dbapi.connect(*cargs, **cparams)
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\pymysql\connections.py", line 358, in __init__
    self.connect()
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\pymysql\connections.py", line 664, in connect
    self._request_authentication()
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\pymysql\connections.py", line 976, in _request_authentication
    auth_packet = _auth.caching_sha2_password_auth(self, auth_packet)
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\pymysql\_auth.py", line 266, in caching_sha2_password_auth
    data = sha2_rsa_encrypt(conn.password, conn.salt, conn.server_public_key)
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\pymysql\_auth.py", line 143, in sha2_rsa_encrypt
    raise RuntimeError(
RuntimeError: 'cryptography' package is required for sha256_password or caching_sha2_password auth methods

[2024-01-27 15:50:50|18956|INFO|base_model.py:91]  session [2649375946832] and [RegressPredict] has an operator: QUERY.
[2024-01-27 15:50:50|18956|INFO|sales_view.py:22]  Regress Predict init successfully
[2024-01-27 15:55:33|3488|INFO|base_model.py:91]  session [2649376539216] and [RegressPredict] has an operator: QUERY.
[2024-01-27 15:55:33|3488|INFO|sales_view.py:22]  Regress Predict init successfully
[2024-01-27 15:55:43|22332|INFO|base_model.py:32]  session [2649376539120] and [RegressPredict] has an operator: ADD.
[2024-01-27 15:55:43|22332|INFO|base_model.py:91]  session [2649376539120] and [RegressPredict] has an operator: QUERY.
[2024-01-27 15:55:43|22332|INFO|sales_view.py:43]  Regress Predict successfully
[2024-01-27 16:44:40|22464|INFO|base_model.py:91]  session [2649377477760] and [Part] has an operator: QUERY.
[2024-01-27 16:44:40|22464|INFO|part_view.py:31]  part init successfully
[2024-01-27 16:44:40|11392|INFO|base_model.py:91]  session [2649375947744] and [Part] has an operator: QUERY.
[2024-01-27 16:44:40|11392|INFO|part_view.py:31]  part init successfully
[2024-01-27 16:49:14|18336|INFO|base_model.py:91]  session [2649377482704] and [Vehicle] has an operator: QUERY.
[2024-01-27 16:49:14|18336|INFO|vehicle_view.py:23]  Vehicle init successfully
[2024-01-27 16:49:14|18264|INFO|base_model.py:91]  session [2649377483088] and [Vehicle] has an operator: QUERY.
[2024-01-27 16:49:14|18264|INFO|vehicle_view.py:23]  Vehicle init successfully
[2024-01-27 16:49:44|2372|INFO|base_model.py:91]  session [2649377486640] and [Part] has an operator: QUERY.
[2024-01-27 16:49:44|2372|INFO|part_view.py:31]  part init successfully
[2024-01-27 16:49:44|19524|INFO|base_model.py:91]  session [2649376542048] and [Part] has an operator: QUERY.
[2024-01-27 16:49:44|19524|INFO|part_view.py:31]  part init successfully
[2024-01-27 16:49:51|22948|INFO|base_model.py:91]  session [2649376539696] and [Vehicle] has an operator: QUERY.
[2024-01-27 16:49:51|22948|INFO|vehicle_view.py:23]  Vehicle init successfully
[2024-01-27 19:39:24|4040|INFO|base_model.py:91]  session [2724849554128] and [Transport] has an operator: QUERY.
[2024-01-27 19:40:32|13040|INFO|base_model.py:91]  session [2258845995728] and [Transport] has an operator: QUERY.
[2024-01-27 19:46:49|2608|INFO|base_model.py:91]  session [2564541106928] and [Transport] has an operator: QUERY.
[2024-01-27 19:46:49|2608|INFO|vehicle_view.py:58]  transport init successfully
[2024-01-27 19:49:10|14508|INFO|base_model.py:91]  session [2564541106448] and [Transport] has an operator: QUERY.
[2024-01-27 19:49:10|14508|INFO|vehicle_view.py:58]  transport init successfully
[2024-01-27 19:49:14|22664|INFO|base_model.py:91]  session [2564541106928] and [Transport] has an operator: QUERY.
[2024-01-27 19:49:14|22664|INFO|vehicle_view.py:58]  transport init successfully
[2024-01-27 19:50:11|22632|INFO|base_model.py:91]  session [2564540870528] and [Transport] has an operator: QUERY.
[2024-01-27 19:50:11|22632|INFO|vehicle_view.py:58]  transport init successfully
[2024-01-27 19:50:12|14800|INFO|base_model.py:91]  session [2564540871968] and [Transport] has an operator: QUERY.
[2024-01-27 19:50:12|14800|INFO|vehicle_view.py:58]  transport init successfully
[2024-01-27 19:50:28|6524|INFO|base_model.py:91]  session [2564541108032] and [Vehicle] has an operator: QUERY.
[2024-01-27 19:50:28|6524|INFO|vehicle_view.py:23]  Vehicle init successfully
[2024-01-27 19:50:28|8736|INFO|base_model.py:91]  session [2564541107840] and [Vehicle] has an operator: QUERY.
[2024-01-27 19:50:28|8736|INFO|vehicle_view.py:23]  Vehicle init successfully
[2024-01-27 19:50:29|16668|INFO|base_model.py:91]  session [2564541108368] and [Transport] has an operator: QUERY.
[2024-01-27 19:50:29|16668|INFO|vehicle_view.py:58]  transport init successfully
[2024-01-27 19:50:30|17440|INFO|base_model.py:91]  session [2564541942032] and [Transport] has an operator: QUERY.
[2024-01-27 19:50:30|17440|INFO|vehicle_view.py:58]  transport init successfully
[2024-01-27 19:51:01|18876|INFO|base_model.py:91]  session [2564541112208] and [Vehicle] has an operator: QUERY.
[2024-01-27 19:51:01|18876|INFO|vehicle_view.py:23]  Vehicle init successfully
[2024-01-27 19:51:02|19528|INFO|base_model.py:91]  session [2564541108224] and [Vehicle] has an operator: QUERY.
[2024-01-27 19:51:02|19528|INFO|vehicle_view.py:23]  Vehicle init successfully
[2024-01-27 20:05:48|2716|INFO|base_model.py:91]  session [2564541946304] and [RegressPredict] has an operator: QUERY.
[2024-01-27 20:05:48|2716|INFO|sales_view.py:22]  Regress Predict init successfully
[2024-01-27 20:05:48|21692|INFO|base_model.py:91]  session [2564541104816] and [RegressPredict] has an operator: QUERY.
[2024-01-27 20:05:48|21692|INFO|sales_view.py:22]  Regress Predict init successfully
[2024-01-27 20:05:49|12716|INFO|base_model.py:91]  session [2564541104528] and [RegressPredict] has an operator: QUERY.
[2024-01-27 20:05:49|12716|INFO|sales_view.py:22]  Regress Predict init successfully
[2024-01-27 20:05:49|18156|INFO|base_model.py:91]  session [2564541104912] and [RegressPredict] has an operator: QUERY.
[2024-01-27 20:05:49|18156|INFO|sales_view.py:22]  Regress Predict init successfully
[2024-01-27 20:24:21|11652|INFO|base_model.py:91]  session [2011644627936] and [RegressPredict] has an operator: QUERY.
[2024-01-27 20:24:21|11652|INFO|sales_view.py:23]  Regress Predict init successfully
[2024-01-27 20:24:23|7700|ERROR|__init__.py:110]  match error, info is 405 Method Not Allowed: The method is not allowed for the requested URL.
[2024-01-27 20:24:23|7700|ERROR|__init__.py:111]  Traceback (most recent call last):
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\flask\app.py", line 844, in dispatch_request
    self.raise_routing_exception(req)
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\flask\app.py", line 453, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\flask\ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\werkzeug\routing\map.py", line 619, in match
    raise MethodNotAllowed(valid_methods=list(e.have_match_for)) from None
werkzeug.exceptions.MethodNotAllowed: 405 Method Not Allowed: The method is not allowed for the requested URL.

[2024-01-27 20:24:48|10456|ERROR|__init__.py:110]  match error, info is 405 Method Not Allowed: The method is not allowed for the requested URL.
[2024-01-27 20:24:48|10456|ERROR|__init__.py:111]  Traceback (most recent call last):
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\flask\app.py", line 844, in dispatch_request
    self.raise_routing_exception(req)
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\flask\app.py", line 453, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\flask\ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\werkzeug\routing\map.py", line 619, in match
    raise MethodNotAllowed(valid_methods=list(e.have_match_for)) from None
werkzeug.exceptions.MethodNotAllowed: 405 Method Not Allowed: The method is not allowed for the requested URL.

[2024-01-27 20:25:01|21588|ERROR|__init__.py:110]  match error, info is 405 Method Not Allowed: The method is not allowed for the requested URL.
[2024-01-27 20:25:01|21588|ERROR|__init__.py:111]  Traceback (most recent call last):
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\flask\app.py", line 844, in dispatch_request
    self.raise_routing_exception(req)
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\flask\app.py", line 453, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\flask\ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\werkzeug\routing\map.py", line 619, in match
    raise MethodNotAllowed(valid_methods=list(e.have_match_for)) from None
werkzeug.exceptions.MethodNotAllowed: 405 Method Not Allowed: The method is not allowed for the requested URL.

[2024-01-27 20:25:07|21388|ERROR|__init__.py:110]  match error, info is 405 Method Not Allowed: The method is not allowed for the requested URL.
[2024-01-27 20:25:07|21388|ERROR|__init__.py:111]  Traceback (most recent call last):
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\flask\app.py", line 844, in dispatch_request
    self.raise_routing_exception(req)
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\flask\app.py", line 453, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\flask\ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\werkzeug\routing\map.py", line 619, in match
    raise MethodNotAllowed(valid_methods=list(e.have_match_for)) from None
werkzeug.exceptions.MethodNotAllowed: 405 Method Not Allowed: The method is not allowed for the requested URL.

[2024-01-27 20:25:58|7364|ERROR|__init__.py:110]  match error, info is 405 Method Not Allowed: The method is not allowed for the requested URL.
[2024-01-27 20:25:58|7364|ERROR|__init__.py:111]  Traceback (most recent call last):
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\flask\app.py", line 844, in dispatch_request
    self.raise_routing_exception(req)
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\flask\app.py", line 453, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\flask\ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\werkzeug\routing\map.py", line 619, in match
    raise MethodNotAllowed(valid_methods=list(e.have_match_for)) from None
werkzeug.exceptions.MethodNotAllowed: 405 Method Not Allowed: The method is not allowed for the requested URL.

[2024-01-27 20:26:35|14216|ERROR|__init__.py:110]  match error, info is 405 Method Not Allowed: The method is not allowed for the requested URL.
[2024-01-27 20:26:35|14216|ERROR|__init__.py:111]  Traceback (most recent call last):
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\flask\app.py", line 844, in dispatch_request
    self.raise_routing_exception(req)
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\flask\app.py", line 453, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\flask\ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\werkzeug\routing\map.py", line 619, in match
    raise MethodNotAllowed(valid_methods=list(e.have_match_for)) from None
werkzeug.exceptions.MethodNotAllowed: 405 Method Not Allowed: The method is not allowed for the requested URL.

[2024-01-27 20:26:53|3428|ERROR|__init__.py:110]  match error, info is 405 Method Not Allowed: The method is not allowed for the requested URL.
[2024-01-27 20:26:53|3428|ERROR|__init__.py:111]  Traceback (most recent call last):
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\flask\app.py", line 844, in dispatch_request
    self.raise_routing_exception(req)
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\flask\app.py", line 453, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\flask\ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\werkzeug\routing\map.py", line 619, in match
    raise MethodNotAllowed(valid_methods=list(e.have_match_for)) from None
werkzeug.exceptions.MethodNotAllowed: 405 Method Not Allowed: The method is not allowed for the requested URL.

[2024-01-27 20:27:09|3760|ERROR|__init__.py:110]  match error, info is 405 Method Not Allowed: The method is not allowed for the requested URL.
[2024-01-27 20:27:09|3760|ERROR|__init__.py:111]  Traceback (most recent call last):
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\flask\app.py", line 844, in dispatch_request
    self.raise_routing_exception(req)
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\flask\app.py", line 453, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\flask\ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\werkzeug\routing\map.py", line 619, in match
    raise MethodNotAllowed(valid_methods=list(e.have_match_for)) from None
werkzeug.exceptions.MethodNotAllowed: 405 Method Not Allowed: The method is not allowed for the requested URL.

[2024-01-27 20:27:37|10728|ERROR|__init__.py:110]  match error, info is 405 Method Not Allowed: The method is not allowed for the requested URL.
[2024-01-27 20:27:37|10728|ERROR|__init__.py:111]  Traceback (most recent call last):
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\flask\app.py", line 844, in dispatch_request
    self.raise_routing_exception(req)
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\flask\app.py", line 453, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\flask\ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\werkzeug\routing\map.py", line 619, in match
    raise MethodNotAllowed(valid_methods=list(e.have_match_for)) from None
werkzeug.exceptions.MethodNotAllowed: 405 Method Not Allowed: The method is not allowed for the requested URL.

[2024-01-27 20:27:40|21064|ERROR|__init__.py:110]  match error, info is 405 Method Not Allowed: The method is not allowed for the requested URL.
[2024-01-27 20:27:40|21064|ERROR|__init__.py:111]  Traceback (most recent call last):
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\flask\app.py", line 844, in dispatch_request
    self.raise_routing_exception(req)
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\flask\app.py", line 453, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\flask\ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\werkzeug\routing\map.py", line 619, in match
    raise MethodNotAllowed(valid_methods=list(e.have_match_for)) from None
werkzeug.exceptions.MethodNotAllowed: 405 Method Not Allowed: The method is not allowed for the requested URL.

[2024-01-27 20:27:42|3376|ERROR|__init__.py:110]  match error, info is 405 Method Not Allowed: The method is not allowed for the requested URL.
[2024-01-27 20:27:42|3376|ERROR|__init__.py:111]  Traceback (most recent call last):
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\flask\app.py", line 844, in dispatch_request
    self.raise_routing_exception(req)
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\flask\app.py", line 453, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\flask\ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\werkzeug\routing\map.py", line 619, in match
    raise MethodNotAllowed(valid_methods=list(e.have_match_for)) from None
werkzeug.exceptions.MethodNotAllowed: 405 Method Not Allowed: The method is not allowed for the requested URL.

[2024-01-27 20:28:02|5676|ERROR|__init__.py:110]  match error, info is 405 Method Not Allowed: The method is not allowed for the requested URL.
[2024-01-27 20:28:02|5676|ERROR|__init__.py:111]  Traceback (most recent call last):
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\flask\app.py", line 844, in dispatch_request
    self.raise_routing_exception(req)
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\flask\app.py", line 453, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\flask\ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\werkzeug\routing\map.py", line 619, in match
    raise MethodNotAllowed(valid_methods=list(e.have_match_for)) from None
werkzeug.exceptions.MethodNotAllowed: 405 Method Not Allowed: The method is not allowed for the requested URL.

[2024-01-27 21:42:53|8492|INFO|base_model.py:91]  session [2773820640224] and [RegressPredict] has an operator: QUERY.
[2024-01-27 21:42:53|8492|INFO|sales_view.py:23]  Regress Predict init successfully
[2024-01-27 21:43:07|16932|ERROR|__init__.py:110]  match error, info is 405 Method Not Allowed: The method is not allowed for the requested URL.
[2024-01-27 21:43:07|16932|ERROR|__init__.py:111]  Traceback (most recent call last):
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\flask\app.py", line 844, in dispatch_request
    self.raise_routing_exception(req)
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\flask\app.py", line 453, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\flask\ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\werkzeug\routing\map.py", line 619, in match
    raise MethodNotAllowed(valid_methods=list(e.have_match_for)) from None
werkzeug.exceptions.MethodNotAllowed: 405 Method Not Allowed: The method is not allowed for the requested URL.

[2024-01-27 21:45:00|18712|ERROR|__init__.py:110]  send_file error, info is [WinError 2] 系统找不到指定的文件。: 'F:\\python\\LogisticsDesign\\back_end\\data.xlsx'
[2024-01-27 21:45:00|18712|ERROR|__init__.py:111]  Traceback (most recent call last):
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "F:\python\LogisticsDesign\back_end\views\sales_view.py", line 61, in download_excel
    return send_file(excel_file, as_attachment=True, download_name='随机森林回归预测2024-1~2024-12.xlsx')
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\flask\helpers.py", line 499, in send_file
    return werkzeug.utils.send_file(  # type: ignore[return-value]
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\werkzeug\utils.py", line 427, in send_file
    stat = os.stat(path)
FileNotFoundError: [WinError 2] 系统找不到指定的文件。: 'F:\\python\\LogisticsDesign\\back_end\\data.xlsx'

[2024-01-27 21:47:16|17480|ERROR|__init__.py:110]  check_parent_directory error, info is Cannot save file into a non-existent directory: '..\..\data\prediction'
[2024-01-27 21:47:16|17480|ERROR|__init__.py:111]  Traceback (most recent call last):
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "F:\python\LogisticsDesign\back_end\views\sales_view.py", line 58, in download_excel
    df.to_excel(excel_file, index=False)
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\pandas\util\_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\pandas\core\generic.py", line 2414, in to_excel
    formatter.write(
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\pandas\io\formats\excel.py", line 943, in write
    writer = ExcelWriter(
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\pandas\io\excel\_openpyxl.py", line 61, in __init__
    super().__init__(
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\pandas\io\excel\_base.py", line 1246, in __init__
    self._handles = get_handle(
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\pandas\io\common.py", line 749, in get_handle
    check_parent_directory(str(handle))
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\pandas\io\common.py", line 616, in check_parent_directory
    raise OSError(rf"Cannot save file into a non-existent directory: '{parent}'")
OSError: Cannot save file into a non-existent directory: '..\..\data\prediction'

[2024-01-27 21:48:52|3972|ERROR|__init__.py:110]  check_parent_directory error, info is Cannot save file into a non-existent directory: '..\..\data\prediction'
[2024-01-27 21:48:52|3972|ERROR|__init__.py:111]  Traceback (most recent call last):
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "F:\python\LogisticsDesign\back_end\views\sales_view.py", line 58, in download_excel
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\pandas\util\_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\pandas\core\generic.py", line 2414, in to_excel
    formatter.write(
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\pandas\io\formats\excel.py", line 943, in write
    writer = ExcelWriter(
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\pandas\io\excel\_openpyxl.py", line 61, in __init__
    super().__init__(
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\pandas\io\excel\_base.py", line 1246, in __init__
    self._handles = get_handle(
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\pandas\io\common.py", line 749, in get_handle
    check_parent_directory(str(handle))
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\pandas\io\common.py", line 616, in check_parent_directory
    raise OSError(rf"Cannot save file into a non-existent directory: '{parent}'")
OSError: Cannot save file into a non-existent directory: '..\..\data\prediction'

[2024-01-27 21:52:54|22392|INFO|base_model.py:91]  session [1838757660608] and [RegressPredict] has an operator: QUERY.
[2024-01-27 21:52:54|22392|INFO|sales_view.py:24]  Regress Predict init successfully
[2024-01-27 21:53:46|21040|INFO|base_model.py:91]  session [1838757663680] and [RegressPredict] has an operator: QUERY.
[2024-01-27 21:53:46|21040|INFO|sales_view.py:24]  Regress Predict init successfully
[2024-01-27 21:53:50|21380|INFO|base_model.py:91]  session [1838757662864] and [RegressPredict] has an operator: QUERY.
[2024-01-27 21:53:50|21380|INFO|sales_view.py:24]  Regress Predict init successfully
[2024-01-27 21:55:07|23404|INFO|base_model.py:91]  session [1838757388176] and [RegressPredict] has an operator: QUERY.
[2024-01-27 21:55:07|23404|INFO|sales_view.py:24]  Regress Predict init successfully
[2024-01-27 21:55:30|11764|INFO|base_model.py:91]  session [1838757659552] and [RegressPredict] has an operator: QUERY.
[2024-01-27 21:55:30|11764|INFO|sales_view.py:24]  Regress Predict init successfully
[2024-01-27 22:23:22|14796|INFO|base_model.py:91]  session [2505045494896] and [RegressPredict] has an operator: QUERY.
[2024-01-27 22:23:22|14796|INFO|sales_view.py:24]  Regress Predict init successfully
[2024-01-27 22:23:35|17352|ERROR|__init__.py:110]  download_excel error, info is 'NoneType' object has no attribute 'replace'
[2024-01-27 22:23:35|17352|ERROR|__init__.py:111]  Traceback (most recent call last):
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "F:\python\LogisticsDesign\back_end\views\sales_view.py", line 60, in download_excel
    start = start.replace("/", "-")
AttributeError: 'NoneType' object has no attribute 'replace'

[2024-01-27 22:24:22|13400|ERROR|__init__.py:110]  download_excel error, info is 'NoneType' object has no attribute 'replace'
[2024-01-27 22:24:22|13400|ERROR|__init__.py:111]  Traceback (most recent call last):
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "F:\python\LogisticsDesign\back_end\views\sales_view.py", line 60, in download_excel
    end = upload_data.get("end")
AttributeError: 'NoneType' object has no attribute 'replace'

[2024-01-27 22:25:27|18760|ERROR|__init__.py:110]  download_excel error, info is 'NoneType' object has no attribute 'replace'
[2024-01-27 22:25:27|18760|ERROR|__init__.py:111]  Traceback (most recent call last):
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "F:\python\LogisticsDesign\bvnev\lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "F:\python\LogisticsDesign\back_end\views\sales_view.py", line 61, in download_excel
    start = start.replace("/", "-")
AttributeError: 'NoneType' object has no attribute 'replace'

[2024-01-27 22:26:43|6460|INFO|base_model.py:91]  session [2079239866208] and [RegressPredict] has an operator: QUERY.
[2024-01-27 22:26:43|6460|INFO|sales_view.py:24]  Regress Predict init successfully
[2024-01-27 22:27:14|18084|INFO|base_model.py:91]  session [2079239866688] and [RegressPredict] has an operator: QUERY.
[2024-01-27 22:27:14|18084|INFO|sales_view.py:24]  Regress Predict init successfully
[2024-01-27 22:27:21|22804|INFO|base_model.py:91]  session [2079239648304] and [RegressPredict] has an operator: QUERY.
[2024-01-27 22:27:21|22804|INFO|sales_view.py:24]  Regress Predict init successfully
[2024-01-27 22:28:35|16616|INFO|base_model.py:91]  session [2079239867648] and [RegressPredict] has an operator: QUERY.
[2024-01-27 22:28:35|16616|INFO|sales_view.py:24]  Regress Predict init successfully
[2024-01-27 22:29:25|12528|INFO|base_model.py:91]  session [2079239866208] and [RegressPredict] has an operator: QUERY.
[2024-01-27 22:29:25|12528|INFO|sales_view.py:24]  Regress Predict init successfully
[2024-01-27 22:32:51|15808|INFO|base_model.py:91]  session [1557399868160] and [RegressPredict] has an operator: QUERY.
[2024-01-27 22:32:51|15808|INFO|sales_view.py:24]  Regress Predict init successfully
