[2024-10-29 12:12:29|12516|ERROR|__init__.py:113]  match error, info is 405 Method Not Allowed: The method is not allowed for the requested URL.
[2024-10-29 12:12:29|12516|ERROR|__init__.py:114]  Traceback (most recent call last):
  File "D:\ruanjian\Python\Python310\lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\ruanjian\Python\Python310\lib\site-packages\flask\app.py", line 844, in dispatch_request
    self.raise_routing_exception(req)
  File "D:\ruanjian\Python\Python310\lib\site-packages\flask\app.py", line 453, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
  File "D:\ruanjian\Python\Python310\lib\site-packages\flask\ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "D:\ruanjian\Python\Python310\lib\site-packages\werkzeug\routing\map.py", line 619, in match
    raise MethodNotAllowed(valid_methods=list(e.have_match_for)) from None
werkzeug.exceptions.MethodNotAllowed: 405 Method Not Allowed: The method is not allowed for the requested URL.

[2024-10-29 12:12:31|28052|ERROR|__init__.py:113]  match error, info is 405 Method Not Allowed: The method is not allowed for the requested URL.
[2024-10-29 12:12:31|28052|ERROR|__init__.py:114]  Traceback (most recent call last):
  File "D:\ruanjian\Python\Python310\lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\ruanjian\Python\Python310\lib\site-packages\flask\app.py", line 844, in dispatch_request
    self.raise_routing_exception(req)
  File "D:\ruanjian\Python\Python310\lib\site-packages\flask\app.py", line 453, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
  File "D:\ruanjian\Python\Python310\lib\site-packages\flask\ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "D:\ruanjian\Python\Python310\lib\site-packages\werkzeug\routing\map.py", line 619, in match
    raise MethodNotAllowed(valid_methods=list(e.have_match_for)) from None
werkzeug.exceptions.MethodNotAllowed: 405 Method Not Allowed: The method is not allowed for the requested URL.

[2024-10-29 12:15:35|3064|ERROR|__init__.py:113]  match error, info is 405 Method Not Allowed: The method is not allowed for the requested URL.
[2024-10-29 12:15:35|3064|ERROR|__init__.py:114]  Traceback (most recent call last):
  File "D:\ruanjian\Python\Python310\lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\ruanjian\Python\Python310\lib\site-packages\flask\app.py", line 844, in dispatch_request
    self.raise_routing_exception(req)
  File "D:\ruanjian\Python\Python310\lib\site-packages\flask\app.py", line 453, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
  File "D:\ruanjian\Python\Python310\lib\site-packages\flask\ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "D:\ruanjian\Python\Python310\lib\site-packages\werkzeug\routing\map.py", line 619, in match
    raise MethodNotAllowed(valid_methods=list(e.have_match_for)) from None
werkzeug.exceptions.MethodNotAllowed: 405 Method Not Allowed: The method is not allowed for the requested URL.

[2024-10-29 12:15:52|6108|ERROR|__init__.py:113]  match error, info is 405 Method Not Allowed: The method is not allowed for the requested URL.
[2024-10-29 12:15:52|6108|ERROR|__init__.py:114]  Traceback (most recent call last):
  File "D:\ruanjian\Python\Python310\lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\ruanjian\Python\Python310\lib\site-packages\flask\app.py", line 844, in dispatch_request
    self.raise_routing_exception(req)
  File "D:\ruanjian\Python\Python310\lib\site-packages\flask\app.py", line 453, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
  File "D:\ruanjian\Python\Python310\lib\site-packages\flask\ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "D:\ruanjian\Python\Python310\lib\site-packages\werkzeug\routing\map.py", line 619, in match
    raise MethodNotAllowed(valid_methods=list(e.have_match_for)) from None
werkzeug.exceptions.MethodNotAllowed: 405 Method Not Allowed: The method is not allowed for the requested URL.

[2024-10-29 12:16:06|30168|ERROR|__init__.py:113]  send_from_directory error, info is 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
[2024-10-29 12:16:06|30168|ERROR|__init__.py:114]  Traceback (most recent call last):
  File "D:\ruanjian\Python\Python310\lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\ruanjian\Python\Python310\lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "D:\ruanjian\Python\Python310\lib\site-packages\flask\app.py", line 260, in <lambda>
    view_func=lambda **kw: self_ref().send_static_file(**kw),  # type: ignore # noqa: B950
  File "D:\ruanjian\Python\Python310\lib\site-packages\flask\app.py", line 308, in send_static_file
    return send_from_directory(
  File "D:\ruanjian\Python\Python310\lib\site-packages\flask\helpers.py", line 552, in send_from_directory
    return werkzeug.utils.send_from_directory(  # type: ignore[return-value]
  File "D:\ruanjian\Python\Python310\lib\site-packages\werkzeug\utils.py", line 574, in send_from_directory
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

[2024-10-29 12:19:40|8564|ERROR|__init__.py:115]  raw_decode error, info is Expecting value: line 1 column 1 (char 0)
[2024-10-29 12:19:40|8564|ERROR|__init__.py:116]  Traceback (most recent call last):
  File "D:\ruanjian\Python\Python310\lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\ruanjian\Python\Python310\lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "D:\py_learn\learn\LogisticsDesign\LogisticsDesign\back_end\views\login_view.py", line 13, in login
    upload_data = json.loads(request.get_data().decode('utf-8'))
  File "D:\ruanjian\Python\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "D:\ruanjian\Python\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\ruanjian\Python\Python310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

[2024-10-29 12:41:10|2936|INFO|base_model.py:91]  session [1693146326080] and [user] has an operator: QUERY.
[2024-10-29 13:03:42|29960|INFO|base_model.py:91]  session [1419523695776] and [user] has an operator: QUERY.
[2024-10-29 13:04:02|19652|INFO|base_model.py:91]  session [1419523697792] and [user] has an operator: QUERY.
[2024-10-29 13:06:59|28984|INFO|base_model.py:91]  session [2053054915840] and [user] has an operator: QUERY.
[2024-10-29 13:07:04|360|INFO|base_model.py:91]  session [2053054918576] and [user] has an operator: QUERY.
[2024-10-29 13:07:06|26996|INFO|base_model.py:91]  session [2053056064880] and [user] has an operator: QUERY.
[2024-10-29 13:07:17|29380|INFO|base_model.py:91]  session [2053056065024] and [user] has an operator: QUERY.
[2024-10-29 13:08:17|15336|INFO|base_model.py:91]  session [1642458571936] and [user] has an operator: QUERY.
[2024-10-29 13:08:17|15336|ERROR|__init__.py:115]  _declarative_constructor error, info is 'password_hash' is an invalid keyword argument for user
[2024-10-29 13:08:17|15336|ERROR|__init__.py:116]  Traceback (most recent call last):
  File "D:\ruanjian\Python\Python310\lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\ruanjian\Python\Python310\lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "D:\py_learn\learn\LogisticsDesign\LogisticsDesign\back_end\views\login_view.py", line 20, in login
    us = user(username=username, password_hash=password_hash_list[0][0], role=0)
  File "<string>", line 4, in __init__
  File "D:\ruanjian\Python\Python310\lib\site-packages\sqlalchemy\orm\state.py", line 566, in _initialize_instance
    with util.safe_reraise():
  File "D:\ruanjian\Python\Python310\lib\site-packages\sqlalchemy\util\langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "D:\ruanjian\Python\Python310\lib\site-packages\sqlalchemy\orm\state.py", line 564, in _initialize_instance
    manager.original_init(*mixed[1:], **kwargs)
  File "D:\ruanjian\Python\Python310\lib\site-packages\sqlalchemy\orm\decl_base.py", line 2142, in _declarative_constructor
    raise TypeError(
TypeError: 'password_hash' is an invalid keyword argument for user

[2024-10-29 13:09:10|31084|INFO|base_model.py:91]  session [2824608802048] and [user] has an operator: QUERY.
[2024-10-29 13:10:52|31420|INFO|base_model.py:91]  session [2642538980656] and [user] has an operator: QUERY.
[2024-10-29 13:11:35|30744|INFO|base_model.py:91]  session [2250213549072] and [user] has an operator: QUERY.
[2024-10-29 13:11:45|14400|INFO|base_model.py:91]  session [2301156369760] and [user] has an operator: QUERY.
[2024-10-29 13:14:01|5028|INFO|base_model.py:91]  session [2600265622736] and [user] has an operator: QUERY.
[2024-10-29 13:14:09|28484|INFO|base_model.py:91]  session [2600265625472] and [user] has an operator: QUERY.
[2024-10-29 13:14:13|32696|INFO|base_model.py:91]  session [2600266788160] and [user] has an operator: QUERY.
[2024-10-29 14:33:50|35332|ERROR|__init__.py:115]  raw_decode error, info is Expecting value: line 1 column 1 (char 0)
[2024-10-29 14:33:50|35332|ERROR|__init__.py:116]  Traceback (most recent call last):
  File "D:\ruanjian\Python\Python310\lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\ruanjian\Python\Python310\lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "D:\py_learn\learn\LogisticsDesign\LogisticsDesign\back_end\views\login_view.py", line 15, in login
    upload_data = json.loads(request.get_data().decode('utf-8'))
  File "D:\ruanjian\Python\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "D:\ruanjian\Python\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\ruanjian\Python\Python310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

[2024-10-29 14:34:22|32864|ERROR|__init__.py:115]  raw_decode error, info is Expecting value: line 1 column 1 (char 0)
[2024-10-29 14:34:22|32864|ERROR|__init__.py:116]  Traceback (most recent call last):
  File "D:\ruanjian\Python\Python310\lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\ruanjian\Python\Python310\lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "D:\py_learn\learn\LogisticsDesign\LogisticsDesign\back_end\views\login_view.py", line 15, in login
    upload_data = json.loads(request.get_data().decode('utf-8'))
  File "D:\ruanjian\Python\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "D:\ruanjian\Python\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\ruanjian\Python\Python310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

[2024-10-29 14:42:48|29796|ERROR|__init__.py:115]  send_from_directory error, info is 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
[2024-10-29 14:42:48|29796|ERROR|__init__.py:116]  Traceback (most recent call last):
  File "D:\ruanjian\Python\Python310\lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\ruanjian\Python\Python310\lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "D:\ruanjian\Python\Python310\lib\site-packages\flask\app.py", line 260, in <lambda>
    view_func=lambda **kw: self_ref().send_static_file(**kw),  # type: ignore # noqa: B950
  File "D:\ruanjian\Python\Python310\lib\site-packages\flask\app.py", line 308, in send_static_file
    return send_from_directory(
  File "D:\ruanjian\Python\Python310\lib\site-packages\flask\helpers.py", line 552, in send_from_directory
    return werkzeug.utils.send_from_directory(  # type: ignore[return-value]
  File "D:\ruanjian\Python\Python310\lib\site-packages\werkzeug\utils.py", line 574, in send_from_directory
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

[2024-10-29 14:43:25|35320|INFO|base_model.py:91]  session [2600266788496] and [user] has an operator: QUERY.
[2024-10-29 14:46:06|34404|INFO|base_model.py:91]  session [2600266789504] and [user] has an operator: QUERY.
[2024-10-29 14:46:08|30776|INFO|base_model.py:91]  session [2600265623216] and [user] has an operator: QUERY.
[2024-10-29 14:46:08|12640|INFO|base_model.py:91]  session [2600265624368] and [user] has an operator: QUERY.
[2024-10-29 14:46:51|26824|INFO|base_model.py:91]  session [2600267484320] and [user] has an operator: QUERY.
[2024-10-29 14:47:23|28372|INFO|base_model.py:91]  session [2600267486336] and [user] has an operator: QUERY.
[2024-10-29 14:48:52|26308|INFO|base_model.py:91]  session [2600267488976] and [user] has an operator: QUERY.
[2024-10-29 14:49:17|16136|INFO|base_model.py:91]  session [2031782389520] and [user] has an operator: QUERY.
[2024-10-29 14:50:20|34356|INFO|base_model.py:91]  session [2466037410368] and [user] has an operator: QUERY.
[2024-10-29 14:51:59|28224|INFO|base_model.py:91]  session [2466037408352] and [user] has an operator: QUERY.
[2024-10-29 14:52:04|31912|INFO|base_model.py:91]  session [2466038623264] and [user] has an operator: QUERY.
[2024-10-29 14:52:24|8524|INFO|base_model.py:91]  session [2466038627680] and [user] has an operator: QUERY.
[2024-10-29 14:53:34|32888|INFO|base_model.py:91]  session [2466038941440] and [user] has an operator: QUERY.
[2024-10-29 14:54:58|27848|INFO|base_model.py:91]  session [2466038627680] and [user] has an operator: QUERY.
[2024-10-29 14:56:43|35660|INFO|base_model.py:91]  session [2466038624080] and [user] has an operator: QUERY.
[2024-10-29 14:57:38|24072|INFO|base_model.py:91]  session [2466037412960] and [user] has an operator: QUERY.
[2024-10-29 14:59:13|33932|INFO|base_model.py:91]  session [1392641173024] and [user] has an operator: QUERY.
[2024-10-29 14:59:37|21600|INFO|base_model.py:91]  session [1392642388128] and [user] has an operator: QUERY.
[2024-10-29 14:59:54|28788|INFO|base_model.py:91]  session [1392642390768] and [user] has an operator: QUERY.
[2024-10-29 15:02:17|29260|INFO|base_model.py:91]  session [1392642721584] and [user] has an operator: QUERY.
[2024-10-29 15:02:32|22336|INFO|base_model.py:91]  session [1392642391344] and [user] has an operator: QUERY.
[2024-10-29 15:04:20|18504|INFO|base_model.py:91]  session [1392642389184] and [user] has an operator: QUERY.
[2024-10-29 15:04:47|31824|INFO|base_model.py:91]  session [1392642722448] and [user] has an operator: QUERY.
[2024-10-29 15:05:44|35248|INFO|base_model.py:91]  session [1392642724560] and [user] has an operator: QUERY.
[2024-10-29 15:06:12|33888|INFO|base_model.py:91]  session [1392642720432] and [user] has an operator: QUERY.
[2024-10-29 15:06:57|32632|INFO|base_model.py:91]  session [1392642729600] and [user] has an operator: QUERY.
[2024-10-29 15:07:13|31496|INFO|base_model.py:91]  session [1392642391008] and [user] has an operator: QUERY.
[2024-10-29 15:07:16|5088|INFO|base_model.py:91]  session [1392642388560] and [user] has an operator: QUERY.
[2024-10-29 15:07:49|33924|INFO|base_model.py:91]  session [1392641171152] and [user] has an operator: QUERY.
[2024-10-29 15:08:27|35796|INFO|base_model.py:91]  session [2726597683728] and [user] has an operator: QUERY.
[2024-10-29 15:11:03|30264|INFO|base_model.py:91]  session [2726598881296] and [user] has an operator: QUERY.
[2024-10-29 15:11:04|29848|INFO|base_model.py:91]  session [2726598881824] and [user] has an operator: QUERY.
[2024-10-29 15:11:07|19116|INFO|base_model.py:91]  session [2726598883264] and [user] has an operator: QUERY.
[2024-10-29 15:11:08|7716|INFO|base_model.py:91]  session [2726599215808] and [user] has an operator: QUERY.
[2024-10-29 15:11:08|34028|INFO|base_model.py:91]  session [2726598880480] and [user] has an operator: QUERY.
[2024-10-29 15:11:14|6428|INFO|base_model.py:91]  session [2726598881296] and [user] has an operator: QUERY.
[2024-10-29 15:11:38|23784|INFO|base_model.py:91]  session [2726599213408] and [user] has an operator: QUERY.
[2024-10-29 15:12:30|32088|INFO|base_model.py:91]  session [2726599214128] and [user] has an operator: QUERY.
[2024-10-29 15:12:45|34116|INFO|base_model.py:91]  session [2726599219024] and [user] has an operator: QUERY.
[2024-10-29 15:13:16|35316|INFO|base_model.py:91]  session [2726599221808] and [user] has an operator: QUERY.
[2024-10-29 15:13:16|32456|INFO|base_model.py:91]  session [2726599224544] and [user] has an operator: QUERY.
[2024-10-29 15:13:17|34248|INFO|base_model.py:91]  session [2726598879520] and [user] has an operator: QUERY.
[2024-10-29 15:13:17|20684|INFO|base_model.py:91]  session [2726598881488] and [user] has an operator: QUERY.
[2024-10-29 15:13:17|32468|INFO|base_model.py:91]  session [2726597686128] and [user] has an operator: QUERY.
[2024-10-29 15:13:18|35652|INFO|base_model.py:91]  session [2726597682672] and [user] has an operator: QUERY.
[2024-10-29 15:13:18|28592|INFO|base_model.py:91]  session [2726599223680] and [user] has an operator: QUERY.
[2024-10-29 15:13:19|12532|INFO|base_model.py:91]  session [2726599219504] and [user] has an operator: QUERY.
[2024-10-29 15:13:20|27156|INFO|base_model.py:91]  session [2726599219216] and [user] has an operator: QUERY.
[2024-10-29 15:13:55|33580|INFO|base_model.py:91]  session [1660737136880] and [user] has an operator: QUERY.
[2024-10-29 15:13:58|34564|INFO|base_model.py:91]  session [1660737139472] and [user] has an operator: QUERY.
[2024-10-29 15:13:58|30580|INFO|base_model.py:91]  session [1660738366448] and [user] has an operator: QUERY.
[2024-10-29 15:13:59|29088|INFO|base_model.py:91]  session [1660738368752] and [user] has an operator: QUERY.
[2024-10-29 15:13:59|33480|INFO|base_model.py:91]  session [1660738371152] and [user] has an operator: QUERY.
[2024-10-29 15:14:03|31436|INFO|base_model.py:91]  session [1660738702304] and [user] has an operator: QUERY.
[2024-10-29 15:14:06|35728|INFO|base_model.py:91]  session [1660738366448] and [user] has an operator: QUERY.
